### ISSUE TITLE
Button in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/utrecht#1546]
Gebaseerd op de [`utrecht-button` component](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-button--default-story).

States:
- active: ingedrukt met pointer
- hover
- focus: geen focus ring
- focus-visible: focus state + focus ring
- liefst ook design voor hover + focus tegelijk
- disabled
- disabled + focus visible: sommige buttons zijn disabled maar moeten wel nog bekend zijn voor screen reader gebruikers, bijvoorbeeld als er een melding staat waarom de button disabled is en hoe je 'm kunt "unlocken"

Varianten:
- primary-action
- secondary-action
- subtle
- button met icon

**Comment by Yolijn** [comment]
Figma duplicate of https://github.com/nl-design-system/backlog/issues/38
