### ISSUE TITLE
Hoofdnavigatie

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/utrecht#1807]
## Wireframes

![Image](https://user-images.githubusercontent.com/24610692/261476366-ed9af497-b7f9-42cb-8556-ee7f2c340391.png)

![Image](https://user-images.githubusercontent.com/24610692/261575937-0283296b-40fd-4f0c-bf6a-18a94a5ec092.png)

![Image](https://user-images.githubusercontent.com/24610692/261600322-69d80d33-8b30-4be5-bae8-2956e20add75.png)

## Description

Horizontale hoofdnavigatie met de belangrijkste paginas van de website. 

- Moet dynamisch zijn qua aantal links
- Responsiveness
- https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-component-navigatie-topnav--docs

**Comment by bddjong** [comment]
@JeroenduC @Ollie-nl Design nodig. O.a. wat is het responsive gedrag van de header?

**Comment by Ollie-nl** [comment]
Op deze Figma pagina staat een schets van een header met hoofdnavigatie met z'n breakpoints
[Figma pagina VTH](https://www.figma.com/file/RW5IlUJIQa64hga1fELyQZ/Local---Gemeente-Utrecht---Bibliotheek?type=design&node-id=331%3A5446&mode=design&t=0tl9jrb9VozCtTZF-1)
