### ISSUE TITLE
Sidebar navigatie

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/utrecht#1811]
## Wireframe
![Image](https://user-images.githubusercontent.com/24610692/261475165-a0904fff-cb33-48d7-aa8c-2e7e2fd2e87d.png)

## Description
Sidebar navigatie component dient als 2e niveau van navigatie. 

### Vragen
- Wat is de responsive variant hiervoor?

**Comment by bddjong** [comment]
@Ollie-nl @JeroenduC Ik zie dat hiervoor wel al een component bestaat. Hoe vergelijkt die met wat we in gedachten hebben voor de VTH website? https://nl-design-system.github.io/utrecht/storybook/?path=/story/web-component-sidenav--default

Wat is de responsive variant?

**Comment by JeroenduC** [comment]
Dit component is niet wat we nu in gedachten hebben (ander project geweest). We werken zsm een nieuwe versie voor je uit.
