### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/utrecht#1813]
## Wireframe
![Image](https://user-images.githubusercontent.com/24610692/261475665-137cff8d-db51-484f-9f6f-caace9607f0d.png)

## Description
Hero banner die de breedte van de pagina (content) bedekt. Eventueel met een tekst overlay

**Comment by bddjong** [comment]
@Ollie-nl @JeroenduC Ook hiervoor zou een design fijn zijn. Is het slechts een pagina content brede afbeelding, of moet er ook tekst over komen te liggen.

**Comment by JeroenduC** [comment]
Ik zou voor de MVP beginnen met een alleen een content brede afbeelding, zonder tekst.

Als de wens boven komt om er tekst boven te doen, lijkt mij dat een prima uitbreiding voor een vervolg oplevering.
