### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/utrecht#1815]
## Wireframe
![Image](https://user-images.githubusercontent.com/24610692/261476609-77eae18b-1467-4848-af35-24c1bc4c3f74.png)

### Responsive gedrag
![Image](https://user-images.githubusercontent.com/24610692/261606193-9f72d71f-ff02-475a-9369-9bdd560b97c7.png)

## Description
Breadcrumb navigatie zodat de gebruiker makkelijk hiërarchisch kan navigeren.

Bij een kleiner scherm verandert de breadcrumb in een enkele link naar de bovenliggende pagina.

### Bestaande componenten 
- [Breadcrumb navigation - Utrecht design system](https://nl-design-system.github.io/utrecht/storybook-react/index.html?path=/docs/react-component-breadcrumb-navigation--docs)
- https://nldesignsystem.nl/richtlijnen/stijl/typografie/

### Technische notes
- Gebruik van container query?

### Design vragen
- Willen we de huidige pagina tonen
- Limit van hoe diep de breadcrumb moet gaan

**Comment by Robbert** [comment]
[CSS Containers, What Do They Know? | Miriam Suzanne | CSS Day 2023](https://www.youtube.com/watch?v=-Fw8GSksUIo&list=PLjnstNlepBvOG299LOrvMFJ8WreCDWWd4&index=9)

**Comment by JeroenduC** [comment]
_Willen we de huidige pagina tonen?_
Voor dit design niet. We weten wel uit de Design meetings met andere gemeentes dat zij de wens wel hebben. Dus een component waar het mogelijk is om te 'togglen' dat je de huidige pagina wel of niet toont zou top zijn.

**Comment by JeroenduC** [comment]
_Limit van hoe diep de breadcrumb moet gaan_
Zo diep als de hierarchie, maar op een bepaald moment zou ik alleen de diepste niveaus laten zien.

In de praktijk voor VTH is het max 3 niveau's diep.

Home > Hoofditem > Thema 

En dan zit je op de content pagina.
