### ISSUE TITLE
Calendar component: clicking outside of current month behaviour

### ISSUE THREAD

**Issue by sergei-maertens** [nl-design-system/utrecht#1823]
When the calendar displays the current month/date and there are some days from the previous month or some days from the next month visible, clicking them to select the date now has some weird behaviour:

* the previous/next month is activated and in view
* the clicked cell is active, rather than the clicked date
* you need to click the date again to effectively select it

Internally we agreed that the expected behaviour would be that the `onDateSelected` callback is called whenever a date is selected, but we also understand that this may be situation dependent. We would like the option to enable this behaviour at least, possibly through a prop `alwaysSelectClickedDate`.

Alternatively, you could also not render the days before/after the current month, which forces the user to use the arrow keys to navigate into different months. This also works around the styling for these "outlier" dates that may now look like the dates themselves are disabled.

**Comment by Robbert** [comment]
Fix released in `npm install --save-exact @utrecht/component-library-react@1.0.0-alpha.353`
