### ISSUE TITLE
BreadcrumbNav and BreadcrumbLink tokens and functionalities

### ISSUE THREAD

**Issue by lencodes** [nl-design-system/utrecht#1880]
Hello 👋🏼 

We've been trying to implement the `BreadcrumbNav` and `BreadcrumbLink` components in opencatalogi.nl. For the most part, it works. However, we did run into some issues which are blocking enough for us to not (yet) implement it fully.

**Tokens**

- `--utrecht-breadcrumb-divider-content` exists, but does not seem to work (when using `appearance="arrows"` the arrows always show as divider, when _not_ using the appearance prop, no divider shows);
- There's a `current` prop available, but we do not see any tokens (nor added functionality) when setting it.

**Other**

- The divider (when using `appearance="arrows"`) also shows at the _end_ of the list, which in our use case a divider should not (see screenshot attached);
- The prop `href` is required, which we would like it _not_ to be (we're using the native `navigate` method from Gatsby; right now we have to set it to an empty string and create a wrapper with `e.preventDefault()`)

![Pasted Graphic](https://github.com/nl-design-system/utrecht/assets/66552932/1941a9b4-44df-403f-895b-8859c711bc1a)

**Comment by Robbert** [comment]
@lencodes ✅ This has been implemented:

```jsx
<BreadcrumbNav label="Kruimelpad">
  <BreadcrumbLink
    href="/"
    index={0}
    rel="home"
  >
    OpenCatalogi
  </BreadcrumbLink>
  <BreadcrumbSeparator>
    <Icon><svg></svg></Icon>
  </BreadcrumbSeparator>
  <BreadcrumbLink
    current
    disabled
    href="/a/b/"
    index={2}
  >
    Categorieën
  </BreadcrumbLink>
</BreadcrumbNav>
```
