### ISSUE TITLE
Storybook: Utrecht > Developers > SVG pagina geeft foutmelding

### ISSUE THREAD

**Issue by reithose** [nl-design-system/utrecht#1967]
Deze pagina geeft de onderstaande fout: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/utrecht-developers-svg--docs 
![image](https://github.com/nl-design-system/utrecht/assets/6649052/7c367f21-21ed-4c2d-b982-c0abfce17907)

**Comment by Robbert** [comment]
Bedankt voor het melden!
