### ISSUE TITLE
Design tokens gelijk trekken tussen tokens.json en voorbeeld-thema

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/utrecht#2234]
Aline kwam erachter dat tokens niet gelijk zijn tussen de utrecht components en het voorbeeldthema. 

https://codefornl.slack.com/archives/C7KDQRXMZ/p1716898519417069

Met dit issue willen we zover mogelijk komen om dat gelijk te trekken, en leren hoeveel tijd dat kost voor losse issues volgende sprint.

Doel: Gelijktrekken van de CSS, tokens.json bij de css component en de tokens uit het voorbeelthema. Waarbij ook gekeken wordt of de Figma component dan aangepast moet worden.

Beginnen met de componenten die Logius gebruikt, dat zijn er vier. Ten minste:

- [ ] Button
- [ ] Alert
- [ ] ...

**Comment by Yolijn** [comment]
Refinen door contact op te nemen met [@Aline Nap](https://codefornl.slack.com/team/U01QZ32D7PZ) en te vragen 

- [ ] Hoe ze die tokens.json gebruikt
- [ ] Welke componenten ze van plan zijn nu direct te gebruiken

**Comment by jeffreylauwers** [comment]
Na het uitzoek werk dat Bryan heeft gedaan hebben we (samen met Roos) even gebeld om de vervolgstappen te bespreken. Hieronder de samenvatting...

**Achtergrond**
Bij het vullen van de NL Design System bibliotheek met voornamelijk Utrecht componenten heb ik enkele tokens toegevoegd die niet in code beschikbaar zijn. Ik heb ik toen '[Comments](https://www.figma.com/design/shhwGcqPLi2CapK0P1zz8O/NLDS---Voorbeeld---Bibliotheek?node-id=1179-3895&t=JAw55aADX3WesqBX-4)' geschreven maar die zijn inmiddels al een jaar oud ;)

**Voorstel**
Om design en code weer gelijk te trekken is het idee om alle tokens die op dit moment niet beschikbaar zijn in code te voorzien van de prefix `todo.`.

**Code referentie**
Voor ik dit 'zoek-de-verschillen' spelletje ga spelen is het fijn dat ik weet waar ik moet kijken voor de laatste versie van de tokens. De storybook met token weergave blijkt namelijk niet altijd alle tokens te bevatten. Bijvoorbeeld Alert ([Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/story/css_css-alert--design-tokens), [Tokens](https://github.com/nl-design-system/utrecht/pull/2243). Daarin trek ik graag samen met Bryan op.

**Wanneer is iets een token waard?**
Voordat ik start zou ik graag nog eens bespreken wanneer je nu een tokens toevoegt. Dit helpt bij het adviseren van andere designers en het opbouwen van todo componenten. Bijvoorbeeld is de token `todo.breadcrumb-navigation.font-family` overbodig, en zou ik voor dat component in Figma ook direct de token `utrecht.document.font-family` kunnen toepassen om zo 'inherit' na te bootsen. Hoe ziet een developer dat dit zo bedoelt is?

**Volgorde van nalopen**
- We beginnen bij de componenten die Logius graag wil gebruiken (Button, Alert, Link, welke nog meer?)
- Daarna volgen de andere componenten die een utrecht prefix hebben, en die ene van Den Haag (Side nav).
- Daarna ook de tokens van todo componenten nalopen. Misschien kunnen er tokens weg (zie onderstaande vraag om af te stemmen)? Misschien kunnen er spacing tokens hernoemd worden op basis van column-gap en row-gap?

**Acties per component**
- Tokens in code up-to-date.
- Zoek de verschillen in Figma.
- Tokens die niet in code bestaan prefix `todo.`.
- PR maken.
- Wat nog meer?

**Afnemers inlichten**
Er zijn enkele designers die de Figma bieb en tokens hebben gedupliceerd.

- Rozerin (Den Haag)
- Rene en Jeroen (Utrecht)
- Aline en Esther (Pra)
- Aline Nap (Logius)
- Martijn (OpenGemeenten)
- Vladimir (Nijmegen)
- Patricia (RIVM)
- Catrina (Almere)
- Marieke en Jana (Groningen)
- Rico, Annet en Wilco (Acato)
- Michaela Tan (Michaela Tan)

Zij zullen geïnformeerd moeten worden en aan hun kant de wijzigingen moeten doorvoeren. Dat is best een klus. Maar ik denk dat ik er een positieve draai aan kan geven. Onder het mom van duidelijker wat er wel beschikbaar is in code én een voorbeeld van hoe je als designers zelf tokens voor een bestaand component kan toevoegen voor jouw organisatie. Wat ons weer duidelijker een beeld geeft van benodigde tokens voor een Candidate component.

**Tijd**
Ik verwacht hier behoorlijk wat tijd voor nodig te hebben. En mijn vermoeden is dat ik ook 1-op-1 hulp zou moeten aanbieden aan de afnemers. Dus zou graag hier de hele sprint op focussen.

**Comment by bddjong** [comment]
Prioriteit hiervoor zou moeten liggen bij de Alert, Button en Link. Vervolgens de Heading en Paragraph.

**Comment by Robbert** [comment]
Onderdeel hier van: https://github.com/nl-design-system/utrecht/issues/2236
