### ISSUE TITLE
StoryBook in React fullscreen mode geeft verkeerde layout

### ISSUE THREAD

**Issue by Ollie-nl** [nl-design-system/utrecht#2618]
Als je in StoryBook een fullscreen wilt openen in React mode geeft deze geen goede layout.

Deze modus hebben we nodig voor een gebruikersonderzoek naar redesign van het klachtenformulier wat we ook willen gaan testen op kleine schermen via StoryBook.

Voorbeeld:
https://nl-design-system.github.io/utrecht/storybook-react/iframe.html?globals=&args=&id=template-form-pages-step-2--two&viewMode=story

https://github.com/nl-design-system/utrecht/tree/template-klachtenformulier

http://localhost:6008/iframe.html?args=&id=klachtenformulier-form-pages-stap-1--one&viewMode=story

**Comment by AliKdhim87** [comment]
Het probleem is opgelost.
https://nl-design-system.github.io/utrecht/storybook-react/iframe.html?args=&id=template-form-pages-step-1--one&viewMode=story
