### ISSUE TITLE
Table CSS classes names

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/utrecht#601]
The BEM classes for the table include `utrecht-table__heading` and `utrecht-table__header`. Looking at the [HTML CSS](https://github.com/nl-design-system/utrecht/blob/main/components/table/html.scss#L19-L29), I believe the naming of these classes is very confusing.

HTML spec refers to `th` as being a **header** cell. But the CSS is using the `__heading` element. Whilst the `thead` selector is using the `__header` class.

**Comment by Robbert** [comment]
@bddjong Great feedback, thanks! I will try to rename the tokens and update the existing themes.
