### ISSUE TITLE
Plan voor versienummers

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/utrecht#685]
Voor semantic versioning willen we het design system automatisch nummeren?

Bijvoorbeeld: elke nieuwe feature een major versie ophogen? 

Of willen we het versienummer kunstmatig laag houden?

**Links**
**Semantic Versioning 2.0.0**
[semver.org](https://semver.org)

**Semantic release** 
[semantic-release.gitbook](https://semantic-release.gitbook.io/semantic-release/)

**Voorbeeld DSO Toolkit:** 
[Voorbeeld DSO toolkit](https://github.com/dso-toolkit/dso-toolkit/blob/master/CHANGELOG.md)

**Comment by frankmijn** [comment]
De belangrijkste vraag is wat je aan wie wilt communiceren met het versienummer. Vandaaruit zou je keuze voor een versionering moeten volgen. De volgende doelgroepen schieten mij nu te binnen:

- Organisaties, je wilt als organisatie afspraken kunnen maken met leveranciers over welke versie(s) ze van het design system ondersteunen terwijl dit wel een redelijk hoeveelheid werk is. 
- Ontwikkelaars, je wilt aan ontwikkelaars duidelijk maken hoe groot de verwachte impact van het uitrollen van een nieuwe versie(s) is
- Afnemers, je wilt aangeven dat de set componenten bij elkaar je in staat stellen om een volledige website te bouwen
- ... 

Ik zou ook het punt willen maken dat je het geheel van het design system een versienummer geeft. En niet afzonderlijke componenten ook nog een versie gaat geven. In ieder geval niet tot daar een sterke behoefte voor is. 

Maar de eerste vraag is volgens mij nog steeds: voor wie willen we wat met het versienummer communiceren?

**Comment by JeroenduC** [comment]
Besproken tijdens retro, @Robbert maakt samenvatting van gemaakte afspraken over versionering.

**Comment by Robbert** [comment]
# Versienummering van een design system

Een nieuwe versie van een design system heeft soms kleine impact voor afnemers van het design system, en soms een grote impact. Versienummers worden gebruikt om de impact te communiceren.

Om de impact op afnemers te beperken, wil je bij het doen van wijzigingen en het bepalen van het nieuwe versienummer nadenken of de wijziging kan worden gedaan met minder impact op afnemers. Soms kunnen een aantal wijzigingen tegelijk worden gedaan in één nieuwe versie, zodat afnemers minder frequent aan de slag moeten met updates.

In alle gevallen is het belangrijk om bij elke versie een duidelijk overzicht van de wijzigingen te publiceren in een *changelog*, zodat afnemers kunnen lezen of de wijziging voor hun gevolgen heeft, en welke migratiestappen er nodig zijn. Veel nieuwe versies bevatten wijzigingen die maar voor weinig afnemers impact hebben, omdat niet iedereen alle onderdelen van het design system gebruikt.

## Major versie

Een nieuwe *major* versie, zoals van 1.0.0 naar 2.0.0, geeft aan dat er werk gedaan moet worden door afnemers om te updaten naar de nieuwe versie — mits de wijziging zit in een onderdeel dat deze afnemer gebruikt.

Een major versie wordt uitgebracht als er een *breaking change* is: een wijziging in bijvoorbeeld code of kleurgebruik waardoor websites of applicaties die de vorige versies gebruikten helemaal of gedeeltelijk niet meer functioneren na een update, voordat migratiestappen zijn gedaan.

Bijvoorbeeld: uit een gebruikerstest blijkt dat component A niet toegankelijk en gebruikersvriendelijk is. Component B wordt ontwikkeld als beter alternatief, en component A wordt verwijderd uit het design system. Websites die component A gebruiken moeten migreren naar component B als ze willen updaten naar de nieuwe major versie en alle versies met kleinere verbeteringen die daarop volgen. Websites die component A niet gebruiken kunnen in de changelog lezen dat er voor hun geen werk nodig en de design system update wordt daar makkelijk en zonder risico geïnstalleerd.

## Minor versie

Een design system wordt vaak uitgebreid met nieuwe mogelijkheden, daarvoor gebruik je minor versie: bijvoorbeeld van 1.0.0 naar 1.1.0. Er wordt bijvoorbeeld een nieuwe design token met een extra kleur gemaakt, of een nieuwe variant van een bestaande component, of zelfs een heel nieuw component. Als afnemer hoef je in theorie niet te updaten naar een nieuwe minor versie als je geen gebruik wilt maken van de nieuwe mogelijkheden. Maar in de praktijk wil je wel updaten, omdat bugs vervolgens alleen worden gefixt in de nieuwste versie.

## Patch versie

Een *patch* versie, zoals van 1.0.0 naar 1.0.1, wordt uitgebracht voor wijzigingen waar afnemers zonder risico een update van kunnen installeren. Sommige patch versies fixen een bug, verbeteren performance of bevatten betere documentatie. Als je als afnemer de mogelijkheid hebt, wordt het aangeraden om regelmatig deze patches te installeren.

Design systems met een klein team brengen meestal alleen patch versies uit voor de nieuwste major en minor versie. Als een afnemer gebruik zou maken van design system 4.2.0 terwijl het design system team inmiddels werkt aan versie 7.0.2, dan moet de afnemer overleg starten met het ontwikkelteam als ze bug fixes nodig hebben voor de oude versie. Het maken en publiceren van fixes voor oude versies vereist vaak specialistische kennis, en daar moet wel capaciteit voor zijn.

## Maak het makkelijk voor afnemers om snel te updaten

Als je wilt dat alle diensten een consistente uitstraling en optimale gebruiksvriendelijke hebben, is het belangrijk dat alle diensten snel gebruik maken van de nieuwste versie van het design system. 

Tijd en aandacht voor de volgende zaken zullen helpen je nieuwste design system succesvol toe te passen bij al je diensten:

- betrouwbare versienummers
- goede communicatie in changelogs
- berichten sturen naar afnemers wanneer er belangrijke updates zijn
- waar mogelijk de impact te beperken
- een handleiding bieden voor migratiestappen

## Versienummers zijn nu niet optimaal

Op dit moment worden verbeteringen van het Utrecht Design System uitgebracht als *alpha*-versie, met een volgnummer. Bijvoorbeeld: `@utrecht/components` versie `1.0.0-alpha.140`. Bij alpha-versies is er voor afnemers geen garantie dat onderdelen stabiel zijn. Component A kan nog bestaan in versie `alpha.140`, maar verwijderd zijn in `alpha.141`.

Op dit moment wordt er geen changelog gepubliceerd met een overzicht van wijzigingen in elke versie. Om een beeld van de wijzigingen te krijgen moeten afnemers op GitHub de *commit messages* nalezen.

## Plan voor betere communicatie

We willen allereerst graag een changelog aanbieden met een overzicht van wijzigingen. Het is gebruikelijk om in het Git-project een `CHANGELOG.md` aan te bieden, waar elke nieuwe versie bovenin het document een heading krijgt met daaronder een opsomming van de wijzigingen.

Hoewel een aanpassing doen in een Markdown-bestand heel makkelijk is, kun je niet goed bepalen welk versienummer je in de header wilt zetten. In de tijd dat je versie 1.2.3 hebt voorbereid en de changelog hebt getypt, kan iemand anders in het team versie 1.3.0 hebben uitgebracht. In een actief design system blijf je bezig om het versienummer en de changelog kloppend te krijgen, en het is bovendien een foutgevoelig proces.

Om snel versies uit te kunnen brengen met het juiste versienummer is het essentieel om het bepalen van het versienummer en het bijwerken van de changelog te automatiseren. Hiervoor kun je bijvoorbeeld gebruikmaken van het de software [semantic release](https://semantic-release.gitbook.io/semantic-release/). Op basis van gestructureerde *commit messages* in Git wordt bepaald of de nieuwe patch, minor of major versie wordt: elke commit moet het formaat van ([Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)) aanhouden. De begeleidende tekst van elke commit wordt door semantic release automatisch verwerkt in de changelog.

We hebben het volgende besloten:
- we maken vanaf nu altijd gebruik van conventional commits
- we gaan een tool installeren ([Semantic Pull Request](https://github.com/marketplace/actions/semantic-pull-request)) om te checken dat de commits het formaat van Conventional Commits volgen, zodat er geen commits worden gemerged die een onjuist versienummer opleveren
- we gaan semantic release installeren zodat de changelog wordt gegenereerd
- er kunnen, zeker in het begin, veel major versies uitkomen waardoor het versienummer snel oploopt: dat is geen probleem op zichzelf
- we gaan proberen alle npm-pakketjes hetzelfde versienummer te geven, zodat duidelijk is welke npm pakketjes in samenhang getest zijn
